### ISSUE TITLE
Nimble text area and text field focus states

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1088]
## 😯 Problem to Solve

@leslieab pointed out that the text area doesn't show any prominent visual indication that it has keyboard focus.
![image](https://user-images.githubusercontent.com/10500124/221979201-ce0da393-957e-4619-9f75-bb2eed96f00f.png)
It currently just changes its border color if it is active. There's no distinction between keyboard focus vs click focus and the border color change doesn't match what's in the visual design spec.

Related, neither the text field nor the text area shows keyboard focus state when it is read-only.

## 💁 Proposed Solution

The [design spec](https://xd.adobe.com/view/33ffad4a-eb2c-4241-b8c5-ebfff1faf6f6-66ac/screen/7c146e4b-c7c9-4975-a158-10e6093c522d/specs/) currently shows a green bar at the bottom of the input area when focused. It also doesn't distinguish between tab focus and clicking into the control (I'm not sure if that is intentional or not).

![image](https://user-images.githubusercontent.com/10500124/221979769-a19a4097-1c51-47d1-abd7-cfa388b5f85c.png)

## 📋 Tasks
- [ ] Reach consensus about desired design and document in this issue
- [ ] Implement design

**Comment by jattasNI** [comment]
First step on this might be for @NIbokeefe to weigh in on whether the current design in XD is up-to-date and what we'd want the focus state to look like for read-only text inputs.

**Comment by leslieab** [comment]
To be clear, read-only Nimble components that are analogous to native text, search, url, tel, email, password, date, month, week, time, datetime-local, and number input types and textareas should enter a focused state when

1. The user has dragged the cursor to highlight text inside of it
2. The user has tabbed to it via keyboard navigation

**Comment by NIbokeefe** [comment]
@jattasNI is your question resolved by @leslieab comment?

**Comment by jattasNI** [comment]
> @jattasNI is your question resolved by @leslieab comment?

@NIbokeefe not quite! That covers when text inputs should be focused but I still want to double check what the focus state should look like:
1. for editable inputs, is the focus state in XD (green line at the bottom of the input) up-to-date? (I vaguely recall a bigger discussion about underlines vs boxes for focus state recently so want to make sure)
2. for read only inputs, should we use the same state? Do we need to update XD to reflect that or is it already there?

**Comment by leslieab** [comment]
Another consideration:

In cases where input components are nested inside other components (in table rows, most notably), they have two slightly different focus states from a functional standpoint. The component can be focused but not interactive (i.e. the component is in a focus state but there is no focus in the field and component keyboard interactions are disabled) or it can be focused and interactive (i.e. the component is in a focus state with focus in the field and component keyboard interactions are enabled). To put it another way, one puts focus _on_ the component and one puts focus _inside_ the component.

Should these be treated the same visually? Should the first use the focus state and the second use the rollover focus state?

**Comment by NIbokeefe** [comment]
@jattasNI 

1.  The green line at the bottom is still the most up to date design for the rollover state (2px green)  and the click-focus (1px green).  I believe what has changed is the Key focus state, which @m-akinc and I discussed.  We realized these inputs on tab focus should trigger focus on the text by highlighting existing text and or placing a cursor in the input field when tabbing to an input.  The double underlines may be present on the tab focus as well to indicate it was a key focus, but most important is that it interacts with the input text without any additional tabbing.  You can immediately start typing in the field after tabbing.  I haven't made any visual changes to the design document.
2.   I don't believe we've identified all the states the read only case requires.  The main interaction points of the read only comment field should be text highlighting and interaction with the scroll bar.  I've drawn the read only comment field as a static component without interactive states (just an interactive scroll bar).  

@leslieab can you confirm what should happen on key focus for read only?

**Comment by NIbokeefe** [comment]
> Another consideration:
> 
> In cases where input components are nested inside other components (in table rows, most notably), they have two slightly different focus states from a functional standpoint. The component can be focused but not interactive (i.e. the component is in a focus state but there is no focus in the field and component keyboard interactions are disabled) or it can be focused and interactive (i.e. the component is in a focus state with focus in the field and component keyboard interactions are enabled). To put it another way, one puts focus _on_ the component and one puts focus _inside_ the component.
> 
> Should these be treated the same visually? Should the first use the focus state and the second use the rollover focus state?

I think these nested situations should be treated exactly how the individual control's key focus is designed.  You can tab to the parent which has unique focus state, then tab to a child which also has a unique focus state.  The focus states are unique to each control's interaction needs but they all are meant to work well together.  So, this should not require any special changes, unless I'm missing some context to a specific situation that hasn't been accounted for.

**Comment by jattasNI** [comment]
Additional questions from the team when triaging this issue:
1. are we sure that we want a focus state in read-only mode? (team hadn't read the above discussion about focus "on" vs "in" a component, perhaps that answers this question)
2. should this apply to the numeric text field too?
3.

**Comment by leslieab** [comment]
Both Chrome and Firefox put focus on read-only input fields (of all types, listed above) when the input has been interacted with via mouse or tabbed to via keyboard navigation; you can test it [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly). I believe we should be consistent with this, unless someone can find ARIA guidelines to the contrary.

I could not figure out how to explain this in a concise way, so bear with me. 

- All interactive components receive input by being interacted with.
- While most components receive input via click, field input components receive input via keyboard interaction.
- When navigating to components via cursor, components indicate that they are able to receive input via hover state. Hover is a visual design state.
- Unlike hover, focus is an interactive state with visual design. Components are not in a focused state unless they are selected to receive input.
- When interacting with components via cursor, click-based components do not have a focus state because the click is the input being received, while keyboard-based components do have a focus state because the click is not the input being received.
- When the user interacts with keyboard-based components using a cursor,  highlighting text and inserting a caret fulfill focus state requirements.
- When the user interacts with keyboard-based components using a keyboard, the text must be highlighted or a caret inserted to fulfill focus state requirements.

All of this works fine, regardless of parent/child relationships, as long as the components are tab stops in the page sequence. The table and everything in it is a single tab stop. Rows in tables are navigated using up/down arrow keys, and components in rows are navigated using left/right arrow keys.

![image](https://user-images.githubusercontent.com/28602266/223540609-5caf8a9c-1d9a-460a-b7a0-c65602009a47.png)

Table and row keyboard interactions are prioritized over component keyboard interaction. The [ARIA guidelines for grids](https://www.w3.org/WAI/ARIA/apg/patterns/grid/) probably explained it best: "While navigation keys, such as arrow keys, are moving focus ... they are not available to perform actions like operate a combobox or move an editing caret inside of a [text field]. The user may need keys that are used for grid navigation to operate elements inside a cell if a cell contains: editable content, multiple widgets, or widgets that utilize arrow keys in their interaction models." 

Their recommendation, which is also my recommendation, is to use enter or f2 to temporarily disable table navigation and enable component editing. So, input field components are focused when they have been navigated to, but that focus state does not support component-level keyboard interactions until the user specifically enters into an "edit mode" which appears and behaves more like a true focus.

![image](https://user-images.githubusercontent.com/28602266/223584182-dbb76877-5a7b-4ff2-bb72-b0246ebdc9ea.png)

I used the existing visual design states for focused and rollover focus to distinguish these modes in my wireframes, but the only requirement I have is that navigation mode focus does not have text selected/caret inserted and edit mode focus does. 

So, input fields essentially need:
- Cursor navigation focus (visual style, text highlight/caret insert appears via user interaction)
- Keyboard navigation focus (visual style, text highlight/caret insert appears by default)
- Table navigation mode focus (same as cursor navigation focus without user interactions)
- Table edit mode focus (same as keyboard navigation focus)

**Comment by fredvisser** [comment]
Closing as read-only text doesn't need a focus visual/state and the table cell work is much broader than this.
