### ISSUE TITLE
Re-export tag names from nimble-angular and update SLE clients

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#1094]
## 🧹 Tech Debt

As part of https://github.com/ni/nimble/pull/1078 : Enable TurboSnap for Chromatic tests - we exported `DesignSystem.tagFor(ComponentClass)` for each nimble component. 

- We should re-export tag names from `nimble-angular` so clients don't have to depend on both it and nimble-components.
- We should update existing usages of DesignSystem.tagFor() [in client code](https://dev.azure.com/ni/DevCentral/_search?action=contents&text=designsystem.tagfor&type=code&lp=code-Project&filters=ProjectFilters%7BDevCentral%7DRepositoryFilters%7BSkyline%7D&pageSize=25&result=DefaultCollection/DevCentral/Skyline/GBmaster//Web/Workspaces/SystemLinkShared/projects/systemlink-lib-angular/src/sl-dialog/sl-dialog-service.ts) to use the new pattern
- We should document this API in README or Storybook

**Comment by jattasNI** [comment]
This came up again [in this SLE PR discussion](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/515680#1688139185). No new requirements from that use case but I did notice that [the pattern of depending on icons in nimble-components is becoming fairly prevalent in SLE's pipes](https://dev.azure.com/ni/DevCentral/_search?action=contents&text=nimble-components%20file%3A*.pipe.ts&type=code&lp=code-Project&filters=ProjectFilters%7BDevCentral%7DRepositoryFilters%7BSkyline%7D&pageSize=25&result=DefaultCollection/DevCentral/Skyline/GBmaster//Web/Workspaces/TestInsights/src/app/results/pipes/step-status-icon.pipe.ts). That pattern will likely change when those grids switch to nimble-table. We could consider prioritizing this before then so that the table users can avoid continuing to depend on nimble-components.
