### ISSUE TITLE
Provide guidance about horizontal separator between tabs and tab contents

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#1205]
## 😯 Problem to Solve

Some applications are rendering a grey line between tabs and tab contents. This is happening inconsistently between apps and requires potentially fragile code that restyles parts of nimble tabs.

From [this discussion](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/473781#1681908989)
![image](https://user-images.githubusercontent.com/10500124/234066761-d39356bf-995c-4fd5-ad7a-011f99414b48.png)

Further discussion of the tech debt involved in adding this line in [plot settings PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/473781#1682091783).

The current places we render a separator include [SLE product and results details](https://dev.azure.com/ni/DevCentral/_search?action=contents&text=ni-nimble-divider-background-color&type=code&lp=code-Project&filters=ProjectFilters%7BDevCentral%7DRepositoryFilters%7BSkyline%7D&pageSize=25&result=DefaultCollection/DevCentral/Skyline/GBmaster//Web/Workspaces/TestInsights/src/app/products/components/product-details/product-details.component.scss).

## 💁 Proposed Solution

1. Get guidance from design about when the horizontal line is necessary and when it isn't
2. Document that guidance in tab stories
3. If the separator is necessary at all, add configuration within Nimble to show / hide it (or enable apps to do so without touching internals of the tab)
4. Update apps to use the new approach

## 📋 Tasks
- [ ] This is a subtask of the feature. (It can be converted to an issue.)
-->

**Comment by jattasNI** [comment]
@leslieab @NIbokeefe this is the issue I mentioned about horizontal separators between tabs and tab contents. We'd love your guidance on whether this separator should appear always, never, or conditionally with certain rules. Currently SLE displays it conditionally but I'm not aware how we decided which places get it.

**Comment by jattasNI** [comment]
Related: #747 might include work to render the horizontal line within slide outs.

**Comment by NIbokeefe** [comment]
**Toolbar:**
Those horizontal lines are important to define the row and plane the tools sit within.  The content is not always full enough to hold the line with enough weight to create the feeling of a horizontal row.  The content can be right and left aligned and we'd often end up with too much ambiguos negative space that doesn't define a row (especially within the center).

The lines were intended to be 2px tall at Black91 10% opacity, or 2px at Black 15 if drawn opaque.  Currently they appear to be 1 px tall.

I don't think it creates any unnecessary or unwanted banding because the fill is the same color in both rows. The division line break up the thickness and helps prevent the row from feeling too large or chunky.  

**Right Slide in:**

The division line in these allow for overflow content senarios to scroll underneath without a drop shadow.  This also keeps continuity with the situation where a search bar is present.  It's a more seamless and logical flow between the different versions of the header.

**Comment by fredvisser** [comment]
I don't see any inconsistency in SLE currently - closing as low ROI.
