### ISSUE TITLE
Select popup stops on DIV - strange overflow behavior

### ISSUE THREAD

**Issue by PetitCalgon** [ni/nimble#1227]
# 🐛 Bug Report

The popup of the "nimble-select" seems to stay inside the DIV on does not popup over DIVs

## 💻 Repro or Code Sample

See yourself on your storybook:
https://nimble.ni.dev/storybook/?path=/docs/select--docs

## 🤔 Expected Behavior

Expect to have the popup of the select pops at the top of the screen and not inside any DIV

## 😯 Current Behavior

When editing the CSS inside the browser, expected behavior (minus popup size/position) is visible by changing position attribute to _"fixed"_ instead of _"absolute"_
Seems to comes from  Fast, as it has the same behavior, which still feels not correct
https://explore.fast.design/components/fast-select (when resizing the DIV around the select, the popup will be very small and not visible at a certain point)

## 🌍 Your Environment

* OS & Device:  Windows
* Browser MS Edge 112 ,  Google Chrome 113,  Mozilla FireFox 112
* Version @ni/nimble-angular: 16.5.22

**Comment by PetitCalgon** [comment]
I fixed it for my code, but the solution is WTF!
Renamed the container class from selection-grid to selectiongrid and it works.

This does not work:
```
<div class="selection-grid">
       <nimble-select.....></nimble-select>
</div>

```
This work:
```
<div class="selectiongrid">
       <nimble-select.....></nimble-select>
</div>
```
Why?

**Comment by atmgrifter00** [comment]
This is a [known issue](https://github.com/microsoft/fast/issues/5363) in FAST. What you'll find is that the issue is closed because they have [addressed it](https://github.com/microsoft/fast/pull/6452) in their new, "unreleased" version of FAST, which Nimble is not using (and won't for some time). That said, you will also see in the comments for the fix that they have provided a possible means of us addressing the problem locally in our component code.
