### ISSUE TITLE
NimbleListOption content in start slot is top-aligned

### ISSUE THREAD

**Issue by epetersoni** [ni/nimble#1254]
# 🐛 Bug Report

Content in the start slot of a NimbleListOption is aligned to the top, while the text is aligned to the vertical center.

## 💻 Repro or Code Sample

```
<NimbleBlazor.NimbleSelect>
    <img slot="start" src="favicon16x16.png" />
    <NimbleBlazor.NimbleListOption><img slot="start" src="favicon16x16.png" /> Image and Text!</NimbleBlazor.NimbleListOption>
</NimbleBlazor.NimbleSelect>
```

## 🤔 Expected Behavior

I would expect the image in the start slot to be vertically center-aligned.

## 😯 Current Behavior

The start slot image is top-aligned.

## 💁 Possible Solution

Explicit styling for list option start slots.

## 🔦 Context

The icon placement looks off:
![image](https://github.com/ni/nimble/assets/77290847/c6735f52-0b21-48a2-95c4-9b849b5a51bc)

## 🌍 Your Environment

* OS & Device: Windows PC
* Browser: Chrome
* NimbleBlazor 11.8.24

**Comment by m-akinc** [comment]
The short answer is that we don't support using the start (or end) slot of the list option element. We talked to our designer about how/if we'd want to support this, and he was resistant to the idea of putting icons in selects or comboboxes. Additionally, if we _were_ to support it, we would want to restrict it to icons that are part of the Nimble library--not arbitrary images. So that said, it would be good to get more context about your use case and whether its something you really feel you need for software we will release.

**Comment by m-akinc** [comment]
There are a number of different design questions to address, if we were to support this:
- Do we support icons in the end slot at all?
    - If so, should they be all the way to the right, at the edge of the listbox?
- Should space be reserved in the left margin if any of the options has an icon?
- Should the selected option's icon be shown in the main part of the control?
    - If so, is that true for comboboxes as well?
- Are images supported in addition to Nimble icons?
- What are the use cases for a select/combobox with icons vs. a picker (which we haven't implemented yet)?

**Comment by mollykreis** [comment]
With #1353, the `start` slot in the list option is now hidden. If/when we add official support for the `start` and/or `end` slots, we'll need to style the slot to be visible again.

**Comment by m-akinc** [comment]
Closing, since we now make it impossible to slot an icon in the list option.
