### ISSUE TITLE
nimble-tokens svg-to-ico task hangs on Windows after a fresh sync (until a retry)

### ISSUE THREAD

**Issue by msmithNI** [ni/nimble#1297]
## 🧹 Tech Debt
Almost any time a developer syncs down the Nimble repo on a Windows machine at a new commit point / on a new branch, and does `npm run build`, the build hangs on the nimble-tokens svg-to-ico task:

```
> @ni/nimble-tokens@6.0.0 build:svg-to-ico
> node build/svg-to-ico.js

Icon asset directory :c:\dev\nimble\packages\nimble-tokens\dist\icons\svg
Output ico directory :c:\dev\nimble\packages\nimble-tokens\dist\icons\ico
Number of icons found to convert: 158
.
```

It would be good to investigate & fix this issue if possible.

## Workaround
Cancel the build and start `npm run build` again

**Comment by msmithNI** [comment]
@m-akinc interesting, it happens way more often for me. Basically anytime I'm on main, and there are new commits to pull down, if I do that + npm install + npm run build, I'll hit it.

**Comment by m-akinc** [comment]
I found a consistent way, but it's weird. If I attempt to delete my `node_modules` folder, it will begin deleting, but then will pop up a dialog saying a file or folder is open in a program. After I cancel that dialog, the next time I try to build `nimble-tokens` will always hang.

**Comment by m-akinc** [comment]
The svg-to-ico package we use is internally using an image processing package called `sharp`. It attempts to process the data for each output size of the icon in parallel. Something about generating multiple sizes at once is causing the hang in one of the `sharp` operations. Because of the way I get it back into the state to hang (i.e. by doing significant filesystem work), I suspect the cause may be caching/paging related. In ProcessExplorer, it looked like the hang was in a memory reallocation function.

The svg-to-ico package is essentially one small function built on top of a couple other packages. We can basically inline that implementation and remove the parallelism from it. That solves the issue. I've put up a PR that does this: https://github.com/ni/nimble/pull/1313. I left a comment to this effect on the PR, but it's really just a proposal. I'm not sure if people will agree this is the right approach.
