### ISSUE TITLE
Add new icon "clock-exclamation_16x16" to the iconography tokens

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#1323]
Add new icon clock-exclamation_16x16 to iconography token library to support the Soliton team.  The designers have requested this icon for an "Expire" metaphor.

*The SVG is attached.

I've also updated this on the P4V document which should build to Baltic over the weekend.  I've updated all UX design libraries as well.

@jattasNI @fredvisser 

## 📌 User Story
![clock-exclamation_16x16](https://github.com/ni/nimble/assets/106594349/81dd228f-6810-404f-93b1-222436ef32e1)

**Comment by NIbokeefe** [comment]
@jattasNI @fredvisser

Can I get a status update for this?

**Comment by jattasNI** [comment]
@NIbokeefe we missed triaging this because it didn't have our usual labels on it. (Might happen if you didn't use one of the issue templates at https://github.com/ni/nimble/issues/new/choose or possibly just GitHub weirdness).

I added the labels now so at the latest we'll find an owner at our weekly Tuesday triage meeting. Hopefully Fred or I can find a few minutes of bandwidth to knock it out before then.
