### ISSUE TITLE
Provide API for non-resizable columns

### ISSUE THREAD

**Issue by atmgrifter00** [ni/nimble#1332]
## 😯 Problem to Solve

There are some column types that would preferably be non-resizable. One example is an icon column, where there is little value in the user interactively sizing the column since the column content is a fixed width. The lone possible exception to this is allowing a user to size such a column below the [`defaultMinPixelWidth`](https://github.com/ni/nimble/blob/a596c7d8c2b8f78f2ce74aea596952c71de33f35/packages/nimble-components/src/table-column/base/types.ts#L54), to allow a user to remove what could be considered a significant amount of unused area in the header to better constrain the column width to its content size.

Considerations:
- What is the header content when a column is smaller than the `defaultMinPixelWidth`? If it's an icon, do we need an affordance to see a text representation (like a tooltip or something better that works on mobile)?
- Is there a way to represent a sorted/grouped column that is smaller than `defaultMinPixelWidth` other than the current approach of separate icons?
- If a column is non-resizable do we hide the column dividers on hover?

## 💁 Proposed Solution

Perhaps this could just be a new mixin with a single attribute: `resizeable: boolean`, or maybe the inverse `disable-resize: boolean`.

**Comment by rajsite** [comment]
Temporarily assigned to @rajsite to reformat the issue to discuss Fixed Width Column more generally. Specifically to capture UX needs around what parts of the header should be shown and the Programmatic API discussion in the original issue

**Comment by rajsite** [comment]
After discussing with @fredvisser and @mollykreis we arrived at some of the following behaviors:
- Until a use case is needed we won't support fixed width columns generally.
- We would support fixed width columns only on icon columns with icon headers.
  - In this case space is not reserved for extra indicators / adorners (sort order, grouping, potential action menus)
  - Only a header icon is shown, not header text
  - Column maintains a fixed width the size of the icon
  - The exact API is undecided, likely needs an HLD update
  - Work to support fixed width only on icon columns captured in: https://github.com/ni/nimble/issues/1873

@fredvisser if we don't know of use cases for a fixed width column outside the anchor column I think we can close this issue. Otherwise we should re-purpose this issue for those use cases.
