### ISSUE TITLE
Remove placeholder concept from table columns

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#1364]
# 🎙 Discussion

In [discussions about the enum columns](https://github.com/ni/nimble/pull/1274#discussion_r1248310568) it was determined that a concept of placeholder / default mappings was inappropriate. In that case a user should pre-format the data and add a state to their mappings to represent the placeholder / default value if they so choose. We aren't trying to compensate for poorly formatted data and trying to distinguish between mapped values, unmapped values, and undefined. If a value is unmapped for enum columns, it renders blank.

The statement was also made that in general placeholders don't make sense for the table. We should prefer to not render invalid data over showing a placeholder as that pollutes the contents of the table. Showing lots of rows of placeholder text in a column just clutters the table. 

There was strong agreement from the team to remove the concept of placeholder / default-mapping from enum column.

A concrete decision for all column types might need buy-in from UX?

**Comment by jattasNI** [comment]
Some additional rationale captured for posterity:
 - in number columns we hope to right align valid values to improve scanning but left align things that don't have a consistent decimal location. Placeholders could make this look ugly with right-aligned valid values and left-aligned placeholder text
 - we aren't aware of specific requests to support placeholder content. If there are any we can add the feature back then, along with guidance about when it should be used rather than showing an empty cell.
