### ISSUE TITLE
Create token for 8px

### ISSUE THREAD

**Issue by mollykreis** [ni/nimble#1518]
## 😯 Problem to Solve

In a few different places throughout our code and client code, we want a spacing of 8px. Therefore, we often do things like `padding: calc($ni-nimble-standard-padding / 2);` or `padding: calc($ni-nimble-small-padding * 2);`. If 8px is going to be a common value in our designs (which it seems like it is already), then we should have a first-class way of using that value without having to calculate it from other token values.

## 💁 Proposed Solution

Create a new token with a value of `8px`. I'm not sure what we want to name it, but it could be something like `$ni-nimble-medium-padding` or `$ni-nimble-half-standard-padding`.

**Comment by rajsite** [comment]
Just mentioning we do have an existing [size ramp convention](https://github.com/ni/nimble/pull/351#discussion_r812364438) even though it's not captured in the [token naming docs](https://github.com/ni/nimble/blob/b49755bcb4948910c5b896b7c11abb64c6aca2cf/packages/nimble-components/CONTRIBUTING.md#token-naming).
Although maybe we should be considering these more like base tokens (represent a fixed value) instead of high-level usage specific tokens (might be "density aware" if theming was to support density and context specific like "row gap", "column padding", or "control height", etc. )

**Comment by jattasNI** [comment]
From Nimble_Components Spacing page on Figma
![image](https://github.com/ni/nimble/assets/10500124/a68e78eb-8c7e-4b81-8cd9-bdaa27742b6a)

**Comment by rajsite** [comment]
During stand-up discussed the following:

- Treat new tokens as a size ramp of base token constants to pick from, no theme aware considerations
- We currently treat standard-padding and small-padding as size ramp values and not high-level token values (used in many places not necessarily "standard padding" related) so build the size ramp with them
- Choose a name scheme that does not require a breaking change to our current size ramp name scheme as that pushes past the ROI
- Expose these base size ramp tokens from nimble tokens with just the awareness that they are not theme oriented, but not with the `base-` prefix either
- Do not treat control-slim-height and control-height as size ramp values. Existing usages generally do seem context aware (the size is used to represent a controls height or a control's slim height).
- Just add the 8px value to the size ramp. Did not see many / any 24px or 32px usages that were not control height related. Add those to the size ramp in the future as needed.

So our base token size ramp we will expose from nimble component tokens are:

small-padding 4px
medium-padding 8px
standard-padding 16px

In the future we likely would want token names that indicate the size ramp and not conflate with a higher-level concept like "padding" but for now no breaking change. Also names for 24px and 32px on the size ramp are TBD and can be added when needed. Probably something like large and extra-large or something.

So concrete actions:

- Add medium-padding token
- Update docs for size ramp tokens to discuss them being used as base token fixed constant values the for size ramp instead of as "padding"
- Add a story page under Tokens/Size ramp to document our size ramp tokens and usage instructions.

**Comment by rajsite** [comment]
Previous discussions on size ramps:

font ramps: https://github.com/ni/nimble/pull/351#discussion_r806312127
spinner sizes: https://github.com/ni/nimble/pull/920#discussion_r1048870872

**Comment by rajsite** [comment]
> Also names for 24px and 32px on the size ramp are TBD and can be added when needed. Probably something like large and extra-large or something.

Reserving large as 24px from discussions in: https://github.com/ni/nimble/pull/1695#discussion_r1411388837

Which also has some discussion on additions to the ramp, i.e. how to do "extra large".
FWIW, as of now I like this direction the most: `large >> large-plus-1 >> large-plus-2 / small >> small-minus-1 >> small-minus-2`. Gives us some wiggle room to put values between levels, i.e standard, standard-plus-1, large, large-plus-2, etc. A number line where standard is zero.
