### ISSUE TITLE
A popover implementation

### ISSUE THREAD

**Issue by kroeschl** [ni/nimble#1583]
## 😯 Problem to Solve

My app, which is in the process of migrating from AngularJS and Bootstrap to Angular and Nimble, uses popovers in several places. This is currently missing from both Nimble and Angular Material despite being included in the Material spec (as a rich tooltip). See for reference:
- https://github.com/angular/components/issues/2691
- https://m3.material.io/components/tooltips/overview

<details>
<summary>Examples of our usage</summary>

![popover-claim](https://github.com/ni/nimble/assets/60117794/14d5907c-92c4-4d0b-8bc4-6a2b6f59a75a)
![popover-other](https://github.com/ni/nimble/assets/60117794/43a15f72-a3d4-4bcc-8ca8-ed9550cd15a7)
![popover-tags](https://github.com/ni/nimble/assets/60117794/17936965-2ea3-43f8-9bb8-43aa5a5b69f1)

</details>

## 💁 Proposed Solution

Some solution exists to provide popover content. This would likely be either a distinct `nimble-popover` attribute or an extension of the existing `nimble-tooltip`. Specifically, we're looking for programmatic open/close and configurable element positioning.

This request might also just be closed and rolled into #309.

**Comment by jattasNI** [comment]
Some notes from our initial discussion:
1. related to #309 but distinct in that this is interactable
2. related to ideas being discussed for NIC 2 Cycle 4 feature adding tooltips to comboboxes
3. might be able to leverage upcoming native popup APIs but those aren't ready yet
4. for the table use cases, you might be able to achieve similar outcomes with an action menu where one of the menu items opens a drawer or dialog that contains the additional context. This would be less immediate than the UX in the gifs but could achieve the same thing.
5. for the picker use case, we'd probably suggest #458 once it's available (but it's not currently scheduled)
6. we don't plan to prioritize this immediately, but thanks for filing it! We'll use this issue to collect more use cases.

**Comment by kroeschl** [comment]
Looking at it some more, I think most of our requirements are met by `nimble-tooltip`. I'm only having trouble with two features:
- Placement of the tooltip (which `fast-tooltip` does support).
- Closing on click outside of the tooltip when `visible` is otherwise manually managed.

I suspect I can work around the second issue, but I'm not sure about the first.

**Comment by jattasNI** [comment]
@kroeschl could you elaborate on your question? Are you asking how to set the `position` attribute on `nimble-tooltip`? What what barrier are you facing and what have you tried?

Also, just in case you hadn't seen, the `nimble-tooltip` is still marked as Incubating [which means](https://nimble.ni.dev/storybook/?path=/docs/incubating-docs--docs) the API may change in the future without notice so it's "use at your own risk". Since your app is internal and we don't have an alternative available this might be ok for you, just wanted to make sure you were aware.

**Comment by kroeschl** [comment]
> Are you asking how to set the `position` attribute on `nimble-tooltip`?

Yes, I'd like to be able to set the [`position` attribute on `fast-tooltip`](https://www.fast.design/docs/components/tooltip/#fields) to control where the tooltip actually displays. For example, in one case I'd like the tooltip to always appear to the left of the anchor element.

> Also, just in case you hadn't seen, the `nimble-tooltip` is still marked as Incubating [which means](https://nimble.ni.dev/storybook/?path=/docs/incubating-docs--docs) the API may change in the future without notice so it's "use at your own risk". Since your app is internal and we don't have an alternative available this might be ok for you, just wanted to make sure you were aware.

Yeah, we're currently doing Nimble version bumps manually so we can check for breakages on incubating components.

**Comment by jattasNI** [comment]
When a Nimble component is derived from a fast-foundation component, the FAST API will typically work on the Nimble one. We aim to document the supported API in the Nimble docs so if it's not documented it means either it's not officially supported or we forgot to document it. In the cases where we don't officially support it, it's usually because we provide (or plan to provide) an opinionated setting for the API and want to discourage clients from customizing it.

I'm not sure which case the `position` attribute on the tooltip falls into but since the component is "incubating" the point is somewhat moot. If it works for you now, feel free to use it while noting the caveat that it might go away later along with any other API changes we make as the tooltip matures.

**Comment by jattasNI** [comment]
I'll close this for now and we can revive it or reference it if another request comes in for similar functionality.
