### ISSUE TITLE
Updating nimble-table data closes any opened context/action menu 

### ISSUE THREAD

**Issue by robert-bob-1** [ni/nimble#1687]
# 🐛 Bug Report
Whenever `nimbleTable.setData(..)` is called, the `nimble-table` closes opened context menus. 
This is problematic for tables that have polling / have data that is constantly refreshed. There are already two apps where this is an issue: Feeds (https://dev.lifecyclesolutions.ni.com/feeds/) 
and LabManagement's work orders (https://dev.lifecyclesolutions.ni.com/labmanagement/workorders?ff-workorders=&ff-workorder-table=).

## 💻 Repro or Code Sample
The sl-table uses this nimble-table, but from my verifications this interruption happens only when nimbleTable.setData is called.
![image](https://github.com/ni/nimble/assets/90975931/5aefe5d8-7b7a-4e93-a8f6-7d46c110bbc4)

## 🤔 Expected Behavior
The context menu should remain opened, just as the selections remain the same even after setting the nimble table data.

## 😯 Current Behavior
Any opened action menu is closed when the table is refreshed with new data:
![nimble-table-context-menu-bug](https://github.com/ni/nimble/assets/90975931/b96ecb52-16f6-41b4-a28b-e72496689ae4)

## 💁 Possible Solution
1. When the data is refreshed the `nimble-table` could open the context menu if any was open at the moment of refresh.
2. More hacky workaround:
  Since we are provided with the `action-menu-beforetoggle`, we could have a `set-action-menu-state` to forcibly open the context menu whenever a refresh happens. 
  However this would then need to be adapted and implemented in the `sl-table` and would still leave this issue in the nimble-table.

## 🔦 Context
It makes it very difficult and annoying to use the context menu buttons in the table when **once every 2-3 attempts the menu closes before you get to select an action** (in the case when polling of data is set to 5 seconds). 

Keep in mind that most grids that we currently have implement some sort of polling with 3-10 seconds intervals. Therefore, if/when the nimble-table will be implemented in place of those grids, this would be a very big issue.

## 🌍 Your Environment

* OS & Device: Windows 10/11
* Browser: Microsoft Edge
* Version: 119.0.2151.58 (Official build) (64-bit)

**Comment by TJ-G** [comment]
@jattasNI - just wanted to make sure this makes it onto your radar. It is making the feeds menu tough to use :)

**Comment by jattasNI** [comment]
@TJ-G @robert-bob-1 This was an intentional design decision for the table. Updating the data can cause the row you're operating on to disappear, change the state of menu items, move the location of the row, etc. Detecting all of these cases and handling them in a way that makes sense for all apps would be expensive and we've been encouraging apps to move away from polling so we decided on the current behavior.

Options available to you include:
1. Reduce the polling frequency
2. Add logic to pause applying data updates to the table while the menu is open (should be possible with the `action-menu-toggle` event)
3. Stop polling entirely and instead implement other workflows like "notification that new data is available, along with a way to refresh the table" or "server pushes updates to client"

**Comment by rajsite** [comment]
Based on discussions from the UI working group on Jesse's suggestions, this issue was closed as not planned

**Comment by TJ-G** [comment]
@jattasNI - Thanks for the background and guidance!

@robert-bob-1 - given the options Jesse listed above, I think trying to implement his 2nd suggestion (pause polling while the menu is open) would be the best for the user without us having to add significantly to the backend. What do you think?

**Comment by robert-bob-1** [comment]
Thanks to Jesse for the great suggestions! We hadn't thought about pausing the polling...

We decided this suggestion works great for our use case, and I already implemented it and pushed the changes.
