### ISSUE TITLE
nimble-button-toggle-tip visual design request

### ISSUE THREAD

**Issue by NIbokeefe** [ni/nimble#1690]
This is an icon that relates to various controls to provide more Information similar to a tool tip but has interactive content in its context menu. 

Requires research around best practices for its states: Hover and Click

Visual design will be similar and inspired by the to the tooltip.

![Image](https://github.com/ni/nimble/assets/106594349/05e918ae-54bf-46c5-acbe-998226fc7edf)

```[tasklist]
### Tasks
- [ ] Define a focus-visible state for the toggle-tip-button
```

**Comment by fredvisser** [comment]
> Some open questions that still need to be answered:
> 
> * Does focus shift to the tooltip content when the toggle-tip is opened? Does it stay on the toggle-tip icon? Does this depend on how the toggle-tip becomes open (e.g. hover vs click)?

No, the focus doesn't shift to the tooltip content when the toggle-tip is opened. It stays on the toggle-tip icon. 

> * Do we need first-class labels on more of our nimble components before this can be used more generally? The original need for this component is the nimble-combobox, which doesn't have a slot for the label.

Excellent question - let's discuss it in https://github.com/ni/nimble/issues/1861

> * Clicking on the label of form fields generally behaves the same as clicking on the field itself, so what does it mean to have an interactable element in the label? Is this an accessibility or usability problem?

I don't think this will be an issue, but we should make sure to have sufficient margin between the label and the icon, so that clicks behave in a reasonable way.
<img width="326" alt="Screenshot 2024-02-22 at 4 28 32 PM" src="https://github.com/ni/nimble/assets/1458528/bccab052-32b1-4999-96e9-220d130a94f3">

> * Are there any tab order considerations with the clickable toggle tip?

The tooltip content should be next in the tab order, so that users can tab into the tooltip content if there are focusable items within.

**Comment by NIbokeefe** [comment]
@m-akinc

It looks like @fredvisser has closed the loop on the open questions Molly had and the visual design spec is complete in Figma.  The only potential remaining needs may be an interaction spec, usage guidance.

Located > Tips
[](https://www.figma.com/file/PO9mFOu5BCl8aJvFchEeuN/Nimble_Components?type=design&node-id=1317%3A39658&mode=dev)

![Image](https://github.com/ni/nimble/assets/106594349/c67bac9d-df4d-4cad-8dc3-1cc4ec3e5afd)
