### ISSUE TITLE
Rich text editor | Alternate approach for getting mentioned href from tiptap editor

### ISSUE THREAD

**Issue by aagash-ni** [ni/nimble#1693]
## 🧹 Tech Debt

Currently `nimble-rich-text-editor` is generating the mentioned hrefs by reserializing to markdown. As the editor is already having all the mentioned node information within its state document( tiptap tree ), hrefs can also be generated from the editor document instead reserializing it, which seems like costly process especially when serialization happens on every key stroke. 

Performance monitoring need to be done for both the cases (re-serializing and extracting it from editor state document) and effective approach needs to be implemented.

Relevant Discussions: https://github.com/ni/nimble/pull/1683#discussion_r1408228542

**Comment by m-akinc** [comment]
@aagash-ni please close this issue when the fix is submitted.

**Comment by vivinkrishna-ni** [comment]
We have addressed this bug by utilizing the Prosemirror APIs, instead of using the serializer to get the current mentioned user details. It is updated in this PR: https://github.com/ni/nimble/pull/1683 and link to the code snippet:

https://github.com/ni/nimble/blob/7787b5639d5a896fe88f50a4a3ba5e7c0875566b/packages/nimble-components/src/rich-text/editor/index.ts#L403C5-L411C6

Hence I am closing this tech debt issue.

**Comment by vivinkrishna-ni** [comment]
We have addressed this by utilizing the Prosemirror APIs, instead of using the serializer to get the current mentioned user details. It is updated in this PR: https://github.com/ni/nimble/pull/1683 and link to the code snippet:

https://github.com/ni/nimble/blob/7787b5639d5a896fe88f50a4a3ba5e7c0875566b/packages/nimble-components/src/rich-text/editor/index.ts#L403C5-L411C6

Hence I am closing this tech debt issue.
