### ISSUE TITLE
Rich text mention users view | Consecutive spaces are not rendering properly in Firefox browsers

### ISSUE THREAD

**Issue by aagash-ni** [ni/nimble#1704]
# 🐛 Bug Report

The `nimble-rich-text-mention-users-view` serves as an internal element for the Nimble rich text components, responsible for rendering user mentions. In the rich text editor, when triggering mentions by typing trigger character `@`, it enters suggestion mode, and the decoration tag becomes `nimble-rich-text-mention-users-view` for user mentions. Under the current approach https://github.com/ni/nimble/pull/1683,  if consecutive spaces are typed after this point, the rendering does not occur, and the spaces persist as a single space. 

## 💻 Repro or Code Sample

Repro: Try giving spaces after adding `@` in the rich text editor by clicking [here](https://60e89457a987cf003efc0a5b-gmvtempdzi.chromatic.com/) in Firefox browser.

## 🤔 Expected Behavior

Multiple spaces should be rendered properly.

## 😯 Current Behavior

https://github.com/ni/nimble/assets/123377167/3c7063c4-8fb2-4ef3-ab27-61667b13fef5

## 💁 Possible Solution
--

## 🔦 Context

Relevant discussions:

https://github.com/ni/nimble/pull/1683#discussion_r1416377550

## 🌍 Your Environment

* OS & Device:  MacOS, Windows on PC
* Browser: Mozilla FireFox
* Version: 119.0.1 (64-bit)

**Comment by vivinkrishna-ni** [comment]
This bug is fixed in the Firefox browser with the latest changes as the decoration tag is being replaced with the default span element in this PR: https://github.com/ni/nimble/pull/1721. We can test it here in [nimble.ni.dev](https://nimble.ni.dev/storybook/?path=/docs/incubating-rich-text-editor--docs).
![firefox-space-issue](https://github.com/ni/nimble/assets/123377523/3a74ab6e-2e37-477f-8bbc-5e24950dd2b9)
