### ISSUE TITLE
Render "nimble-rich-text-mention-users-view" as decoration tag in rich text editor

### ISSUE THREAD

**Issue by aagash-ni** [ni/nimble#1716]
## 🧹 Tech Debt

Currently `nimble-rich-text-editor` uses tip-tap native configuration `span` as a decoration node in `mention-extension`. But the actual design is to use the `nimble-rich-text-mention-users-view` as a decoration tag in the suggestion mode and with the `disabled-editing` attribute in committed mode (After the user got selected).

Here are few difficulties while rendering `nimble-rich-text-mention-users-view` as a decoration tag in suggestions:

1. In Android ( Chrome ), selecting the user from the popup by clicking `Return` on the keyboard is not happening properly.

![Android](https://github.com/ni/nimble/assets/123377167/6bf624bb-60cd-4844-811b-05c28dfb263a)

2. In macOS (Safari) and IOS (chrome), removing the contents in the decoration tag by giving `backspace` is removing the whole decoration tag instead of the last character in it. 

![safari](https://github.com/ni/nimble/assets/123377167/7e0f81ae-79ad-4e0b-aaa1-dda5cd37119c)

**Comment by vivinkrishna-ni** [comment]
For point 2, in macOS, it is an issue with the Safari browser. To verify that I created a contenteditable div and render a shadow DOM element within it. In which pressing backspace removes the entire content instead of the last character in the node in Safari whereas in other browsers like Chrome and Firefox on macOS, it removes only the last character. Here is the example to test it: https://stackblitz.com/edit/typescript-avgrtp?file=package.json,index.html

So I created a bug in WebKit: https://bugs.webkit.org/show_bug.cgi?id=266700. Once it is fixed in WebKit, we can consider rendering the decoration tag as a `nimble-rich-text-mention-users-view` in edit mode.
