### ISSUE TITLE
Additional icons for execution control

### ISSUE THREAD

**Issue by darrenbiel** [ni/nimble#1844]
## 😯 Problem to Solve

SystemLink Enterprise has a new workflow for test plan execution control. This will include UI actions for start, pause, resume, abort, and end actions. Additionally, we will add actions for test plans for generate, deploy, and view dashboard. It is desirable to have nimble icons for some or all of these actions.

## 💁 Proposed Solution

Identify existing icons or create new icons for these actions. 

- Start - nimble-icon-play
- Pause - nimble-icon-pause
- Resume - Reusing nimble-icon-play seems inappropriate because they will be visible at the same time.
- Abort - Either abort or end could use nimble-icon-stop-square, but the other would need to be different.
- End - Either abort or end could use nimble-icon-stop-square, but the other would need to be different.
- Generate (as in build software) - Likely a new icon
- Deploy - Likely a new icon
- View dashboard - Could be nimble-icon-eye or nimble-icon-gauge-simple. Or could be a new icon.

**Comment by m-akinc** [comment]
@NIbokeefe FYI

**Comment by NIbokeefe** [comment]
@jattasNI @darrenbiel 

Start and Stop/Abort, (potentially Resume) should be colored, because that's how those icons are intended to be implemented holistically.  Pause is always grey and the others would likely be grey as well.

From Nimble-Iconography:
<img width="304" alt="Screen Shot 2024-02-21 at 3 07 03 PM" src="https://github.com/ni/nimble/assets/106594349/77a139c3-b47a-4aee-8aeb-5a9e8c052da9">

**Comment by NIbokeefe** [comment]
@darrenbiel @jattasNI @fredvisser 

Here are designs for each icon.  I didn't do versions because we already had existing metaphors for each item, but I did rework each icons to get it aligned with Nimble iconography standards.

I'd recommend not using the word "test" redundantly if the context is clear.  If you must use the word test after each item it should be in sentence case.

Let me know if this works for you all, or if you have any additional feedback/request.  

![Image](https://github.com/ni/nimble/assets/106594349/585e4d50-876b-4dc2-9320-8595c6918b43)
![Image](https://github.com/ni/nimble/assets/106594349/14c2d930-628f-45aa-b304-9e838aa24850)

**Comment by jattasNI** [comment]
Re-added triage tag to discuss colored icons and to assign a dev owner to do the icon integration.

**Comment by NIbokeefe** [comment]
Icons to implement: 

I made a last minute update to Resume which now looks like @darrenbiel original design.  This works better as a collection in size, placement and metaphor.

**Icons for Darren's request:**

horizontal-triangle-outline_16x16
Tags: Resume, Play, Start, Go, Now
![Image](https://github.com/ni/nimble/assets/106594349/f687320e-e70d-4613-bf04-6de3e5ea47e3)

inward-squares-three_16x16
Tags: Deploy
![Image](https://github.com/ni/nimble/assets/106594349/cae88c84-96b0-4940-bc69-cbe690fb8504)

three-circles-ascending-container_16x16
Tags: Generate, Produce
![Image](https://github.com/ni/nimble/assets/106594349/4f45021a-f418-4ef3-b645-51cc62e37f5f)

square-x_16x16
Tags:  Abort, End, Stop, Quit
![Image](https://github.com/ni/nimble/assets/106594349/55e62695-12e9-43b2-a89c-fb01aa39ca07)



**Additions:**
These are some upcoming icons we may need and so I'm combining with this task.

outward-squares-three_16x16
Tags: Undeploy
![Image](https://github.com/ni/nimble/assets/106594349/2a70eab8-831a-4bf4-9c40-f9e5bdae3019)

eye-dash_16x16
Tags: Hide, Show, View, Remove, 
![Image](https://github.com/ni/nimble/assets/106594349/899f2cb7-26d0-47de-9bc0-75b5e1066f1c)

**Updates:**
There was a bug in this design which I noticed while doing this task.

skip-arrow_16x16
![Image](https://github.com/ni/nimble/assets/106594349/f4500b94-035b-4d24-8824-95fb169b3ca8)

**Comment by jattasNI** [comment]
We still want to support colored icons but in a team meeting we decided to start by integrating these icons with our existing monochromatic approach. We can cover colored icons as part of #1802
