### ISSUE TITLE
Broom icon

### ISSUE THREAD

**Issue by MileaRobertStefan** [ni/nimble#2138]
# 🎨 Visual Design Request

Can we add a broom icon?

## 📌 Request Background

We need a icon that suggest "clean".

## 🎯 Core Requirements

To look like a broom.

## 🍆 Non-requirements

It should be made out of wood not plastic.

**Comment by NIbokeefe** [comment]
Hi @MileaRobertStefan 

We don't use a broom similar to LabVIEW for "clean-up" in our most modern iconography, the team has been using two-four-point-stars to indicate clean.  In "Fuse" (our older design system, but still mostly modern metaphors) a broom has been used for "clear" in certain context, but we've since moved to better more standard metaphors around clear, delete, remove.

I'm planning for clean or clean up to remain these sparkly stars vs a broom.

Here's the revised version I've created to include in Nimble:

![Image](https://github.com/ni/nimble/assets/106594349/35b1c18c-4352-40ec-b8a8-7bcb945124e3)
![Image](https://github.com/ni/nimble/assets/106594349/9fd6e0bd-9802-4423-9038-92850e425a64)

Let me know this will cover your needs and I'll get it implemented as a token for you.

Thanks,
Brandon

CC: @jattasNI  @fredvisser

**Comment by MileaRobertStefan** [comment]
Looks good!

**Comment by NIbokeefe** [comment]
@fredvisser @jattasNI Please add to token library.

![two-four-point-stars_16x16](https://github.com/ni/nimble/assets/106594349/63c411d6-5fe3-45d9-ab4e-4b772879973d)

Tags: Clean, Clean up, Stars, Sparkle

**Comment by jattasNI** [comment]
@MileaRobertStefan the icon above is [now available](https://nimble.ni.dev/storybook/?path=/docs/components-icons--docs): `nimble-icon-sparkles`.
