### ISSUE TITLE
Table select via keyboard sometimes behaves as if Shift is pressed when it isn't

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#2222]
# 🐛 Bug Report

In the SLE files app if I use keyboard navigation to select a table row, it sometimes behaves as if Shift is pressed (selecting multiple rows with a single checkbox toggle) even when it isn't.

I saw this a couple times in macOS Firefox but then after refreshing the page I haven't been able to reproduce it. I tried in other browsers and in Storybook and wasn't able to reproduce there. 

I'd recommend we do some code inspection to see if we can hypothesize any way that this could happen and that another person try to reproduce it too. If we find something then great, if not I have no problem closing this with no changes.

## 💻 Repro or Code Sample

https://dev.lifecyclesolutions.ni.com/files/
1. tab to the table
2. arrow to a row's selection checkbox
3. space to toggle it
4. arrow to a different row that's a few rows away
5. space to toggle it

## 🤔 Expected Behavior

6. the new row is selected but the ones in between aren't

## 😯 Current Behavior

6. sometimes all the rows in between are selected

## 🔦 Context
https://dev.lifecyclesolutions.ni.com/files/

## 🌍 Your Environment

macOS Firefox

**Comment by fredvisser** [comment]
I could also reproduce it in Safari - it seemed 100% reproducible if I selected the row with the checkbox focus vs selecting when the whole row was focused, but it's also no longer reproducible for me as well 🤷‍♂️

 

https://github.com/ni/nimble/assets/1458528/38ee1650-9d40-430e-9d43-3ab286058c58

https://github.com/ni/nimble/assets/1458528/c0361b7b-7cb3-4e1b-a0c7-6d03c07299aa

**Comment by m-akinc** [comment]
At least scan the code to see if we can find a way this could happen.

**Comment by m-akinc** [comment]
I found a couple variations on how to reproduce this (it is not browser specific). The key is that you have to press the shift key while the document has focus, then release the shift key while something outside the document has focus.
1. From a page with a table on it, press shift+tab until the focus goes to the browser's chrome. Let go of shift and tab back to the table. At this point, selections will behave as if shift is still pressed.
2. Same as #1, but instead of shift+tab'ing out of the document, do shift+esc.

I'm putting up a PR that fixes this.
