### ISSUE TITLE
Follow up cleanup from Angular 13 and 14 update

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#270]

**Comment by jattasNI** [comment]
As part of this or as follow-up tech debt, we could see if we can adopt `TestBed` settings for `errorOnUnknownElements` and/or `errorOnUnknownProperties` instead of the `test.ts` workarounds we added in #757.

The new settings were added in Angular 14 and are described in this comment: 
https://github.com/angular/angular/issues/36430#issuecomment-1117801535

**Comment by rajsite** [comment]
We are on Angular 14 now  and should make sure these are addressed. Added triage label to take a look at it.
