### ISSUE TITLE
Fix accessibility issues in Angular Example app

### ISSUE THREAD

**Issue by fredvisser** [ni/nimble#280]
# 🐛 Bug Report

We should fix all remaining accessibility issues in the Angular Example app, and change the Lighthouse budget to 100% required to pass

**Comment by rajsite** [comment]
Removing the blocked tag as I think the current working decision is we own our select and combobox implementations and can improve accessibility ourselves. The score has also dropped lower and likely impacted by more than just those issues.

**Comment by jattasNI** [comment]
Next step is to create issues for each accessibility problem and prioritize them individually. Then we should close this issue: we don't see much value in tracking all these issues together.

**Comment by msmithNI** [comment]
Marked as team review since the select/combobox label change is now in, so we can discuss if there's further work to do here.

Lighthouse reports:
- [Before select/combobox built-in label change](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1722636864491-43521.report.html) : Accessibility = 85
- [After](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1722639228008-80394.report.html): Accessibility = 93

**Comment by m-akinc** [comment]
Make sure remaining problems are tracked in separate issues, update the threshold back to 90 and then close this.

**Comment by jattasNI** [comment]
Menu header issues are already tracked by #185

I added the table issues to #2285

I filed #2345 for the rich text issue
