### ISSUE TITLE
Add tests for stateless directives

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#318]
## 📌 User Story
As part of #220 an [example test](https://github.com/ni/nimble/pull/220/files#diff-e7eb866212909a71b1174b7f3c84824a3bd2c12cccb6115ea033fce6500d2782) was added to cover [testing the different template binding mechanisms.](https://github.com/ni/nimble/blob/0d1599ccb1fb11032d2a48b44360a9a37e7140a9/angular-workspace/projects/ni/nimble-angular/CONTRIBUTING.md#testing) 

We should expand that test coverage to all properties for all controls.

One potential way to avoid writing explicit tests for the behavior of each property may be to write reusable decorators that can be well-tested once and give confidence that, for example, boolean, string, or number binding work as expected. There is an [Angular Issue](https://github.com/angular/angular/issues/8968) discussing such a decorator approach that raises some concerns with that approach that should be evaluated to see if they are still issues today.

Edit: This thread also gives some [example decorators](https://github.com/angular/angular/issues/14761). If we end up using any we should make sure to preserve strict type checking.

Edit: [Input setter coercion](https://v12.angular.io/guide/template-typecheck#input-setter-coercion) sounds like something we may need when switching bavk to ivy an using strict templates.

**Comment by jattasNI** [comment]
The directives still needing tests are:
- [ ] list option
- [ ] menu item
- [ ] tab
- [ ] theme provider
- [ ] tree view

Most of these just have trivial properties like `disabled` so it shouldn't be much work to add these tests.

**Comment by mollykreis** [comment]
I couldn't easily try out the `@Input` `transform` functions since nimble is still on Angular 15, but I read through the docs. I think we could use the `transform` configuration as a different way of invoking our `toBooleanProperty`, `toNumberProperty`, etc functions. And, in some cases, we could use some built-in conversion functions provided by Angular. However, from the perspective of each individual directive, I don't think there would be a much/any reduction in the amount of code needed. Therefore, I'm not convinced that moving to using `@Input` `transform` functions will give us any more confidence that we can reduce the number of boilerplate tests we have for our directives.
