### ISSUE TITLE
Breadcrumb click area is larger than area that gives mouse cursor feedback

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#557]
# 🐛 Bug Report

You can click a breadcrumb item anywhere in its underlying div to navigate to its page. But the mouse cursor only changes to indicate that it's operable and the URL preview for the browser only appears when hovering over the link.

https://user-images.githubusercontent.com/10500124/168139383-fa8b5449-83f6-4371-bf11-8e7d5345fd4f.mov

## 💻 Repro or Code Sample

SLE Files app: https://enterprise-dev.systemlinkcloud.io/systems/20UCS1L10N--SN-PF2N6M5J--MAC-8C-8C-AA-F9-72-56/files

## 🤔 Expected Behavior

Either:
1. only the link is clickable
2. the whole item is clickable but it gives standard link feedback (cursor and URL preview)

## 😯 Current Behavior

Entire area clickable but only link gives feedback indicating so.

## 🔦 Context

Reported by Gergo at the UI Working Group

**Comment by mollykreis** [comment]
@msmithNI, it looks like the bug involving `delegatesFocus: true` and the component entering the `:focus-visible` state too aggressively has been fixed in chromium. The second bullet point in your comment should no longer be the case.

**Comment by mollykreis** [comment]
From the bit of debugging I did, this appears to be an Angular-only issue. The `RouterLinkWithHref` directive, which the `NimbleBreadcrumbItemRouterLinkWithHrefDirective` extends, adds a click handler that performs the navigation. The `NimbleBreadcrumbItemRouterLinkWithHrefDirective` applies to the entire `nimble-breadcrumb-item` rather than just the anchor element within its shadow root. As a result, clicking anywhere within the `nimble-breadcrumb-item` will cause the navigation to occur.

**Comment by m-akinc** [comment]
I looked into swallowing the click event if it was outside the bounding rect of the anchor element (in breadcrumb item's shadow DOM), but no luck. The `RouterLinkWithHref``s `s `onClick` method doesn't get the event, so we don't know the coordinates of the click to compare against the bounding box of the anchor. I tried to think of other solutions, but came up empty.
