### ISSUE TITLE
A11y labels on increment/decrement buttons of numeric are not localized

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#617]
# 🐛 Bug Report

In some cases, we use icon buttons (i.e. buttons with `content-hidden`) within other components, like the number field (for the inc/dec buttons). In those cases, we still provide a hidden label string for the sake of accessibility. Those strings are not getting localized.

## 💻 Repro or Code Sample

N/A

## 🤔 Expected Behavior

Even hidden labels should be localized.

## 😯 Current Behavior

Hidden labels are not localized.

## 💁 Possible Solution

N/A

## 🔦 Context

We want screen readers to work well with our components on non-English systems.

## 🌍 Your Environment

N/A

**Comment by atmgrifter00** [comment]
@rajsite or @jattasNI, what is our strategy for dealing with these kinds of localization problems? It would be helpful when someone looks at this issue that there is some documented strategy (even if it's "we have no strategy to address this") in place in the comments so we know we can either ignore it, or know what the problem space is for the issue (i.e. "solve localization at large for Nimble").

**Comment by jattasNI** [comment]
Our strategy so far has been to expose an API that allows clients to provide all the user-facing strings that the component needs. We can provide default English values for those strings but document that apps should provide their own localized values for them.

I don't see us trying to add localization infrastructure for Nimble itself any time soon.

If you can think of a CONTRIBUTING doc to document this policy, feel free to add a note as part of the fix for this.

**Comment by m-akinc** [comment]
Fixed by #1328
