### ISSUE TITLE
Align Typography tokens naming with HTML element naming?

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#773]
# 🎙 Discussion
Could we make our typography tokens ordered similarly to how elements are ordered in HTML. We don't have to copy the elements, themselves, just make the ordering the same direction.

**Current nimble typography (from largest to smallest):**

- Headline_2
- Headline_1
- Title_3
- Title_2
- Tile_1
- etc.

**HTML typography(from largest to smallest):**
- H1
- H2
- H3
- H4
- H5
- etc.

I think it will make understanding the differences between each nimble size a little more intuitive since it will match a known system and it could help with mapping typography to html elements (headline_1 to h1, for example).

**How would it change our current tokens? It would just invert the order of them, like this:**
- Headline_1
- Headline_2
- Title_1
- Title_2
- Tile_3
- etc.

**Comment by rajsite** [comment]
As a reference here are the current [theme-aware token naming conventions](https://github.com/ni/nimble/blob/6ce4aec3b23f2901394aeab71150503fe9d09dcd/packages/nimble-components/CONTRIBUTING.md#token-naming):

> `[element]-[part]-[state]-[token_type]`
> 
> 1. Where **element** is the type to which the token applies (e.g. 'application', 'body', or 'title-plus-1').
> 2. Where **part** is the specific part of the element to which the token applies (e.g. 'border', 'background', or shadow).
> 3. Where **state** is the more specific state descriptor (e.g. 'selected' or 'disabled'). Multiple states should be sorted alphabetically.
> 4. Where **token_type** is the token category (e.g. 'color', 'font', 'font-color', 'height', 'width', or 'size').

And discussions on how we ended up at the current type scale: https://github.com/ni/nimble/pull/351#discussion_r811522139

As a reference, the breakdown we currently use is:
1. `base tokens` (raw values, i.e. green) `->`
2. `theme-aware tokens` (higher level abstractions, i.e. "popup border color") `->`
3. `component` (the popup for a nimble menu button / popup of select / popup of combobox / tooltip all use the high-level "popup border color").

This works pretty well for "web application" controls (buttons, inputs, tabs, etc) because we made our own (nimble-button, nimble-number-field, nimble-text-field) but we have not figured out a plan for "web page" controls (H1, span, section, header, main, content, footer, etc).

I don't think we are likely to make equivalents for those (nimble-h1, nimble-h2, nimble-span, etc) so we don't have a mapping of theme-aware tokens to "web page" controls yet.

As of today the user would have to create the mapping themselves:

```
h1 { font: $ni-nimble-headline-plus-1-font }
h2 { font: $ni-nimble-headline-font }
/* etc... */
```

Using nimble in "web pages" (where few to no controls are used, most content like headers, links, images) hasn't come up a whole bunch yet so we haven't addressed it yet.

I think we likely would do something the user can **opt-in** to like add an option to nimble-theme-provider to apply default styles to the page for those controls, ie `<nimble-theme-provider with-default-styles>` or offer a stylesheet that is included in apps. Something like that is not in the backlog yet.

> How would it change our current tokens?

Depends on what layer we are talking about:

Base tokens? That is more of a communication tool between designers and nimble developers. We can do what is most appropriate. Application authors should pretty much only be using theme-aware tokens instead of base tokens so changes should not impact them heavily (web applications should all use the theme-aware tokens which is only available in the web but other environments like desktop apps consume the base tokens directly so changes to base tokens might impact desktop app authors the most).

Theme-aware tokens? I think we would need to discuss more what the implications are. Currently the theme-aware tokens are targeting abstract parts of elements and not specific elements. So these would be a major change to our token organization.

Components? Discussed above but our "web application" components are not impacted, however the "web page" component experience could be improved. That improvement would likely be in the form of helper components or stylesheets, likely not in token renaming. We could add "component-specific tokens" to the chain ("base" -> "theme-aware" -> "component-specific" -> component) but that is not something we have found necessary yet.

**Comment by nate-ni** [comment]
> I need to look more into it, but I think this is what things like Tailwind do.

Yup, it looks like Step 1 of Tailwind is to override all user agent styling implied by the tag. https://play.tailwindcss.com/1MrwNfew9u

**Comment by nate-ni** [comment]
> And discussions on how we ended up at the current type scale: [#351 (comment)](https://github.com/ni/nimble/pull/351#discussion_r811522139)

That's very helpful to see the background. Thanks!
FWIW, Adobe has since update their tokens to TShirt Sizes (XL, XXL, XXXL). It has some benefits...and drawbacks, but just wanted to provide that for awareness. 
https://opensource.adobe.com/spectrum-css/typography-heading.html
https://spectrum.adobe.com/page/heading/#Size


![image](https://user-images.githubusercontent.com/109235103/194382810-26355382-27c6-4ed9-85d4-a7cb66cea578.png)

You are correct that we largely focus on web applications, so our priorities are correct. There are a couple of instances where providing more "web page" optimized tokens will still be helpful:
1. Areas of a web app where there is web page type content...Getting Started page, for example
2. Areas where our clients need to piece together their own component or otherwise fill-in where there isn't a pre-existing component from Nimble.

While it is 100% subjective, trying to use the current typography token naming for web page content in counterintuitive and confusing. Some of that has to do with the naming, but part of it has to do with the absence of a documented strategy towards applying it to web page content. 
(So I don't forget what I meant by that statement later down the line, I'm going to put more detail in this).
- I'm don't know how we expect a user to apply our theme aware tokens to text elements. We don't provide tokens for everything (we are missing margins, for example). 
- I don't know if we intend a user to map our tokens to elements (h1, h2, h3, etc.) and which ones are the suggested ones.
- I don't know if we intend to a user to decouple the tag from the style altogether.

Some tooling would help as well since this could alleviate problems like "What size would XL mean". TailwindCSS has a nive VSCode extension to help with that, as an example.

![image](https://user-images.githubusercontent.com/109235103/194385118-214b4592-fc3f-49d1-964b-bc4864f0ca1b.png)

**Comment by fredvisser** [comment]
Not a priority in the medium term
