### ISSUE TITLE
Use rem for CSS Units to improve accessiblity?

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#774]
# 🎙 Discussion
I have noticed that we are using `px` in our tokens for sizing. Should we be using something relative like `rem` that would respect a user's browser font size setting? I believe that work towards making things more accessible. WCAG recommends `em` instead of `rem` but I think the base argument is mildly the same in regards to scaling content better.

https://www.w3.org/TR/WCAG20-TECHS/C14.html#C14-examples

**Comment by rajsite** [comment]
Some related discussion from the NITech Run-Through: The Designer & Developer's Guide to Accessibility meeting I'll capture here:

[8/12 10:29 AM] Katie DePue
TIL Nimble uses relative font sizes!!

[8/12 10:29 AM] Milan Raj
> Katie DePue TIL Nimble uses relative font sizes!!

It doesn't actually 😅

[8/12 10:30 AM] Katie DePue
yet?

[8/12 10:31 AM] Milan Raj
Tough Question. A lot of our designers work in fixed pixel sizing so it would be a pretty big shift at the moment to do relative sizes. I'd like to get there at some point

[8/12 10:31 AM] Christopher Griego
Milan how do we hatch the plan to get there? You estimating 1 year out? 10 years out? 

[8/12 10:41 AM] Milan Raj
Nimble does do responsive layouts, the UIs scale with the size of the page, normal zoom isn't prevented. Just want to emphasize the experience isn't broken when zooming or scaling,

But user's overriding the font sizes on the page (ie not zooming, but just increasing the font size) won't work as expected. Kinda like that Google demo. Google's homepage likely works fine when you zoom but if you try and override the fonts with larger fonts it won't respond naturally. Some things might get clipped in their boxes.

At the moment we aren't trying to readjust our designs to accommodate that type of change. The adjusting to user's font selection approach works better for "web page" style content where the exact structure and placement isn't a big deal (think wikipedia) compared to "web applications" where structure and placement and sizing matter more (think google maps, google calendar). Currently nimble is mostly used in "web applications" where user picked font sizes would be very difficult / impractical to accommodate for.

But we want nimble to be general purpose so if users want to use nimble in "web page" content that could increase the priority of making responding to user chosen font sizes possible.

**Comment by nate-ni** [comment]
Created a branch that adds StyleDictionary transform to convert our size units to rem for css and scss outputs.
Just a concept, at the moment.

632b7a451ce2b3ff81149f01adf46f51aa2d2254

**Comment by rajsite** [comment]
Discussed at stand-up: to test the effect of using rem units instead of px units in the branch, one can update the "root" font-size, ie the font that is applied to the `<html>` element.

Some examples of how to set that:

```html
<html style="font-size: 32px">
```

```css
html {
    font-size: 32px;
}
```

```js
document.documentElement.style.fontSize = '32px'
```

More info in the [MDN Values and units: ems and rems topic](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#ems_and_rems).

Some open questions:

- Are we going to support it for all controls?
- What size ranges would we support? Miniscule or very large fonts would both require a lot more design work I think.
- How would it impact layouts, i.e. grids, slideout panels, etc, that have very precise layouts
- What would our testing strategy be (related to what we would support)? As-is there are exisiting issues in the ui:
    ![image](https://user-images.githubusercontent.com/1588923/194936737-d63de2fa-6eb2-494d-86c2-09e30b9dc81b.png)
- Maybe we need a more nuanced strategy? Something like controls won't support it, only specific areas will use rem units like body content, header content.
- Maybe we don't respond to arbitrary set sizes on root (rem units) but instead have different modes, ie can set the `<nimble-theme-provider font-size="small|medium|large">` and we respond to those with new px sizes?

**Comment by nate-ni** [comment]
It looks like the values that aren't changing are hard coded and not generated from or referenced to the tokens. But I don't know if the file I'm referencing in a generated file from a build pipeline or manually created.


from`/nimble/packages/nimble-components/src/theme-provider/design-tokens.ts`

```
// Component Sizing Tokens
export const controlHeight = DesignToken.create<string>(
    styleNameFromTokenName(tokenNames.controlHeight)
).withDefault('32px');
export const smallPadding = DesignToken.create<string>(
    styleNameFromTokenName(tokenNames.smallPadding)
).withDefault('4px');
export const standardPadding = DesignToken.create<string>(
    styleNameFromTokenName(tokenNames.standardPadding)
).withDefault('16px');
export const labelHeight = DesignToken.create<string>(
    styleNameFromTokenName(tokenNames.labelHeight)
).withDefault('16px');
export const borderWidth = DesignToken.create<string>(
    styleNameFromTokenName(tokenNames.borderWidth)
).withDefault('1px');
export const iconSize = DesignToken.create<string>(
    styleNameFromTokenName(tokenNames.iconSize)
).withDefault('16px');
export const drawerWidth = DesignToken.create<string>(
    styleNameFromTokenName(tokenNames.drawerWidth)
).withDefault('784px');```

**Comment by rajsite** [comment]
> It looks like the values that aren't changing are hard coded and not generated from or referenced to the tokens. But I don't know if the file I'm referencing is a generated file from a build pipeline or manually created.

`design-tokens.ts` is manually created. It is the mapping from base tokens to high-level tokens (a manual process). It may have tokens that are not expressed in terms of base tokens because we didn't find a way in xd (like timing) or they weren't defined when we needed them or are incorrectly not using base tokens when they should.

**Comment by nate-ni** [comment]
Additional info shared by @rajsite 
https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/

**Comment by fredvisser** [comment]
Revisit when we tackle client mobile usecases.

**Comment by rajsite** [comment]
> Revisit when we tackle client mobile usecases.

@fredvisser makes sense, we should also make sure to frame that work as something like "small screen" to capture / test the cases of mobile vs zoom vs large font: https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/#accessibility-considerations-5
