### ISSUE TITLE
@mdx-js/react fails to install

### ISSUE THREAD

**Issue by TrevorKarjanis** [ni/nimble#806]
## 🧹 Tech Debt

`@mdx-js/react` is a dependency of `@storybook/addon-docs`, but it doesn't always get installed. This causes the nimble-components build to fail. #708 declares it as a dependency to resolve the issue. [Jesse suggests](https://github.com/ni/nimble/pull/708#discussion_r1017044769) the issue be investigated further. Storybook issue [18094](https://github.com/storybookjs/storybook/issues/18094) may be related.

**Comment by rajsite** [comment]
This was resolved by #1000 by migrating to mdx2 experimental support in Storybook 6.4.

The "surprsing" explicit dependency on mdx-js/react is still needed but we no longer have runtime errors in storybook about mdx/react support which was the state after the Angular update. And after #1000 we no longer after peer dependency version conflicts due to mdx-js/react when rebuilding the lock file.

After Storybook 7 is released there will be a significant change (mdx2 is the default and builder switches to vite) so any extra clean-up will happen then. I think this issue is fine to close till then.
