### ISSUE TITLE
Pinned columns

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#848]
## 😯 Problem to Solve
This is a development configuration freezing the first/last column (or first/last **_n_** columns) in a table. This is helpful when a table is very wide and the first column should remain visible when horizontally scrolling.

From table spec this is phrased, "Pin columns: columns remain fixed during horizontal scrolling"

## 💁 Proposed Solution
- [x] #892

## 🤔 Open Questions
1. Have we enabled horizontal scrolling?
2. Do we need to be able to enable pinning for **_last_** columns?
   - It's not unheard of, but is this something we need?
   - https://material.angular.io/components/table/overview#sticky-rows-and-columns
4. Should there be an interactive version of this feature (so the end user can "pin/freeze" a column)?

## 🖼️ References/Prior Art
https://user-images.githubusercontent.com/109235103/205920352-456669aa-0586-466c-9792-9088c1d9a2dd.mov

**Comment by atmgrifter00** [comment]
Rough prototype from innovation day: [https://github.com/ni/nimble/tree/table-pinned-columns](https://github.com/ni/nimble/tree/table-pinned-columns) ([Storybook](https://60e89457a987cf003efc0a5b-cohvfnnpop.chromatic.com/?path=/story/incubating-table-column-configuration--grouping)).

Things of note:
- Using 'sticky' for the frozen entities seems like the only viable implementation route (as opposed to something like separate containers for pinned and unpinned elements).
- Using display of `inline-grid` seems necessary to get sticky behavior to work properly (at least for containers that were using `grid` before).
- Offsetting header row using CSS `left` for scrolling purposes interferes with setting CSS `left` for making header content sticky (the latter of which seems necessary). Instead of setting the CSS `left` property, we can instead set the `scrollLeft` of the element containing all of the header content (requiring implementation in code-behind). This seems like it also might require its CSS `overflow` to be explicitly be set to `hidden`.
- Cell elements will likely require having their background explicitly set so that appropriate visual clipping occurs when a scrollable column is dragged passed a pinned column.
- Assumption is that all pinned columns will be rendered in order before unpinned columns (not implemented in prototype)

Visual things to finalize:
- Should there be any explicit visual indicator denoting the border between pinned and unpinned columns?
- Perhaps things like the group rows and collapse-all/selection checkboxes should _always_ be sticky/pinned. Only the cell content can actually be scrolled.

Remaining unprototyped work:
- Dealing with arbitrarily large header content (with/without selection checkboxes, etc...)
- Sizing column headers that are pinned can have improper visual behaviors, like the column header remaining in place, and the right divider moving when it shouldn't (like when dragging the left divider left) 
- Applying the same pattern for keeping the header content pinned to the cell content.

**Comment by fredvisser** [comment]
Not prioritized against current client requirements.

**Comment by rajsite** [comment]
@hellovolcano feel free to capture notes, referenced design systems, and links to prototypes in this issue.

**Comment by rajsite** [comment]
@mollykreis's pinned column prototype ([branch](https://github.com/ni/nimble/tree/sticky-pinned-front-column-prototype)) ([storybook](https://60e89457a987cf003efc0a5b-uxtmfvpalv.chromatic.com/?path=/docs/components-table-column-mapping--docs))

**Comment by hellovolcano** [comment]
Based on client needs and discussion with @rajsite @mollykreis and @jattasNI , I plan to implement a scoped version of the pinned column feature. It will:

- Only support fixed-width columns. 
- Only the pinned columns will be sticky, and not the selection or collapse 
- Is not interactive

I adapted Molly's prototype to implement what I listed above ([prototype draft PR](https://github.com/ni/nimble/pull/2964)). You can see the pinned column in the table column mapping story.

I currently do not have visual styling implemented, but will work with Brandon to get his thoughts on how we should style that

**Comment by jattasNI** [comment]
@hellovolcano we had a quick sync with @rajsite and @mollykreis this morning to talk about behavior and API design to expedite our typical spec processes. Here are our recommendations:


1. API should be `pin-location="left"` (and `null`/default meaning not pinned) to allow for future `pin-location="right"`
2. It's permitted to pin multiple columns. The DOM order determines the display order within each set of columns with a given `pin-location`.
   - we didn't discuss this but if it saves implementation time to only support a single pinned column initially that would be fine but we should document it and mark the table invalid if more than one is specified
4. The attribute is set by client programmatically, not by users interactively
5. pinned columns and their headers do not scroll horizontally. Everything else continues to scroll (e.g. selection checkboxes, expand/collapse twisties, group rows, non-pinned columns)
6. For now only fixed width columns can be pinned. Not necessarily a permanent decision but allows us to defer discussion about how resizing would behave. We should mark the column as invalid if it's pinned and not fixed width.
7. Other invalid states:
   - ~~pinned and hidden~~ although pinning has no effect on a hidden column this should be a valid state to simplify client code for transitory states like keeping a column pinned and toggling it between visible and hidden

**Comment by rajsite** [comment]
First stage of pinned columns merged designed as in [comment above](https://github.com/ni/nimble/issues/848#issuecomment-4595571069) in #2964 as contributed by @hellovolcano (ty for the awesome work!). Closing the issue and future feature requests / revisions (right pinned columns, resizeable pinned columns) should have new issues with HLDs and UX/UI design review as normal
