### ISSUE TITLE
Table hierarchical data support

### ISSUE THREAD

**Issue by nate-ni** [ni/nimble#861]
## 😯 Problem to Solve
The table needs to support displaying a hierarchical data source.
From table spec: "Provide hierarchy via the data"

Excludes [leaf mode](https://github.com/ni/nimble/issues/1759) and [dynamic child loading](https://github.com/ni/nimble/issues/1758), which are tracked separately.

## 💁 Proposed Solution
 - [x] #890

## 🖼️ References/Prior Art
![Image](https://user-images.githubusercontent.com/109235103/200389498-b34805b6-07f3-4b07-a783-c0696d56e139.png)

**Comment by jattasNI** [comment]
We'd really like to get a fix for #1162 before proceeding with this issue. Without it we'd have to put large TanStack workarounds into our implementation.

**Comment by jattasNI** [comment]
A client using the old grid [mentioned](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/548655#1692975724) that they want larger data sizes for hierarchy than what we've claimed support for to date. The specs grid can contain up to 5000 parent nodes, each with up to 10 children, meaning 55000 rows of data.

**Comment by atmgrifter00** [comment]
Rough prototype from innovation day: [https://github.com/ni/nimble/tree/table-pinned-columns](https://github.com/ni/nimble/tree/table-pinned-columns) ([Storybook](https://60e89457a987cf003efc0a5b-cohvfnnpop.chromatic.com/?path=/story/incubating-table-column-configuration--grouping)).

Things of note:
- Using 'sticky' for the frozen entities seems like the only viable implementation route (as opposed to something like separate containers for pinned and unpinned elements).
- Using display of `inline-grid` seems necessary to get sticky behavior to work properly (at least for containers that were using `grid` before).
- Offsetting header row using CSS `left` for scrolling purposes interferes with setting CSS `left` for making header content sticky (the latter of which seems necessary). Instead of setting the CSS `left` property, we can instead set the `scrollLeft` of the element containing all of the header content (requiring implementation in code-behind). This seems like it also might require its CSS `overflow` to be explicitly be set to `hidden`.
- Cell elements will likely require having their background explicitly set so that appropriate visual clipping occurs when a scrollable column is dragged passed a pinned column.
- Assumption is that all pinned columns will be rendered in order before unpinned columns (not implemented in prototype)

Visual things to finalize:
- Should there be any explicit visual indicator denoting the border between pinned and unpinned columns?
- Perhaps things like the group rows and collapse-all/selection checkboxes should _always_ be sticky/pinned. Only the cell content can actually be scrolled.

Remaining unprototyped work:
- Dealing with arbitrarily large header content (with/without selection checkboxes, etc...)
- Sizing column headers that are pinned can have improper visual behaviors, like the column header remaining in place, and the right divider moving when it shouldn't (like when dragging the left divider left) 
- Applying the same pattern for keeping the header content pinned to the cell content.

**Comment by fredvisser** [comment]
@fredvisser - Add requirements for a table loading indicator and confirm that leaf mode is not required for Tag table.
