### ISSUE TITLE
Support "primary" appearance variant for toggle and menu buttons

### ISSUE THREAD

**Issue by m-akinc** [ni/nimble#897]
## 😯 Problem to Solve

Our toggle and menu buttons don't support the "primary" appearance variant, but there doesn't seem to be a good reason for that. For consistency, all our button types should support the same appearances.

## 💁 Proposed Solution

Move the appearance variant attribute (with the "primary" value) into our shared button interface and styles.

**Comment by mollykreis** [comment]
Do we have use-cases for this or designs that indicate these are valid scenarios? I don't think we should add variants to components that our designers wouldn't want people to use just because the components are similar (i.e. all buttons).

A related note is that our "primary" appearance isn't up-to-date right now for the button. We have issue #663 to track the work needed to update our button to match the current spec. Therefore, (1) I don't think we should do the work now to add outdated states to other components, and (2) we should figure out whether or not all the loud/quite & primary/normal variants.

**Comment by jattasNI** [comment]
Assigned to Nate to drive conversation with UX about which button variants we want to support long term.

**Comment by nate-ni** [comment]
We do not need "Primary" appearances for toggle or menu buttons. 

The only buttons we need them for are `nimble-button` and the `nimble-anchor-button` since it is mimicking a `nimble-button`.
