### ISSUE TITLE
Improve cross browser test coverage: enable WebKit tests on CI

### ISSUE THREAD

**Issue by jattasNI** [ni/nimble#990]
## 🧹 Tech Debt

We currently run unit tests in only Chromium and our Chromatic tests in Chromium and Firefox. More test coverage would be better to help catch issues like #984 via automated rather than manual testing.

Possible directions (might split this issue to track these separately)

1. ~~add commands to run unit tests on other browsers and run them locally (I tried this briefly and discovered several failing in Safari and Firefox)~~ **Done**

2. run tests as part of our PR build. Would require some research to find out best practices for getting agents with Firefox and webkit **Done for Firefox**
   - mac agents? Probably not as they cost many times more than default Linux agents
   - Using Playwright's cross-platform webkit build? Related: #705
   - ~~we'd also want a way to disable specific tests in specific browsers. We could consider the approach we use for WebVIs where certain tags are added to test names.~~ **Done**

3. Consider whether we want to run cross-browser testing for nimble-tokens, nimble-angular, and nimble-blazor

Already done by @fredvisser :
- Once it's available, enable Chromatic testing in Safari (at a recent meeting we heard it was coming in February)

```[tasklist]
## Related PRs
- [ ] #998 
- [ ] #1067 
```

**Comment by msmithNI** [comment]
Created #1074 and #1075 track our current autotest failures in WebKit and Firefox.

**Comment by msmithNI** [comment]
- If we need to disable tests in specific browsers, the [karma-jasmine-spec-tags package](https://github.com/mnasyrov/karma-jasmine-spec-tags) is an option. They released a new version 2 weeks ago that now looks like it works with our Karma/Jasmine versions (Mert had code to pull it in as part of #1156 )
- In order to enable WebKit tests for the CI build, we still need to follow up with the [karma-webkit-launcher](https://github.com/google/karma-webkit-launcher) author about the issues we were seeing with the Playwright WebKit binaries not getting cleaned up. There's [explicit code skipping child process cleanup if isCI=true](https://github.com/google/karma-webkit-launcher/blob/8a4f20e2292f9b46fed7a4434020d297f6e398d0/index.js#L256) so we should inquire why that is / see if there could be a configuration option added for it or something.

**Comment by msmithNI** [comment]
@jattasNI that's mostly accurate.

Initially I thought that it would be a quick fix for karma-webkit-launcher but I'm not sure about that anymore. A few months ago I tried essentially forking karma-webkit-launcher (copied the code to a local source file/ Karma plugin) to test out the process cleanup code that was already there, but I didn't get it working. (That was [this branch](https://github.com/ni/nimble/commits/users/masmith/temp-webkit-tests/) / [this build result](https://github.com/ni/nimble/actions/runs/7483483021/job/20368797511))

So options are probably
- File an issue/discusson with karma-webkit-launcher: Optimally we could point them to a smaller reproducing repo than Nimble (since we have multiple projects/ test runs all using the same browser Playwright binaries)
- Potentially fork the launcher / make our own version (not a ton of code, we'd probably end up with less than karma-webkit-launcher since it also supports non-Playwright test runs)
